server:
  port: 8001
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_member
    username: train_member
    password: train_member
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.lyc.member.mapper: trace




