GET http://localhost:8000/member/passenger/query-list
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MzM1MzA3NzQsIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjE4NjQ1NzYzOTc5MTQyNzk5MzYsImV4cCI6MTczMzYxNzE3NCwiaWF0IjoxNzMzNTMwNzc0fQ.DiaI9s50VoheKupAUR5_dnkjU4Grq_gtHXrIYT7B3ok

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MzM0ODg4OTksIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjE4NjQ1NzYzOTc5MTQyNzk5MzYsImV4cCI6MTczMzU3NTI5OSwiaWF0IjoxNzMzNDg4ODk5fQ.Ox9yOJIqSPtuT9n6eRsf4vm69Q2jv2ECV06PKG4wGYo

{
  "name": "test",
  "idCard": "123",
  "type": "1"
}





