server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8001
#          uri: lb://member
          predicates:
            - Path=/member/**
      globalcors:
        cors-configurations:
          '[/**]': # 适用于所有路由
            allowedOrigins: "http://localhost:9000"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "Authorization"
            allowCredentials: true
            maxAge: 3600




