server:
  port: 8002
  servlet:
    context-path: /business
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_business
    username: train_business
    password: train_business
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: business
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.lyc.business.mapper: trace



