server:
  port: 8003
  servlet:
    context-path: /batch
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_batch
    username: train_batch
    password: train_batch
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/batch/**/*.xml
logging:
  level:
    com.lyc.business.mapper: trace




